version: '3.8'
services:
 db:
  image: postgres:alpine
  restart: always
  environment:
   - POSTGRES_USER=admin-user
   - POSTGRES_PASSWORD=admin-password
   - POSTGRES_DB=assignmentDb
  ports:
   - '5432:5432'
  volumes:
   - postgresdb:/var/lib/postgresql/data

 pgadmin:
  depends_on:
   - postgres
  image: dpage/pgadmin4
  restart: unless-stopped
  environment:
   - PGADMIN_DEFAULT_EMAIL=admin@admin.com
   - PGADMIN_DEFAULT_PASSWORD=root
  ports:
   - '5050:80'

volumes:
 postgresdb:
  driver: local
